version: '3.8'

services:
  water-quality-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped

  water-quality-streamlit:
    build: .
    command: streamlit run src/app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - water-quality-api
